// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZVqG2fV1wII9BC1hFA6_qlNhuXqry3ZU',
    appId: '1:941925661587:web:e8468dd133d0c5997ac666',
    messagingSenderId: '941925661587',
    projectId: 'jukebox-996de',
    authDomain: 'jukebox-996de.firebaseapp.com',
    databaseURL: 'https://jukebox-996de-default-rtdb.firebaseio.com',
    storageBucket: 'jukebox-996de.firebasestorage.app',
    measurementId: 'G-SDXVEHEQ0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl-6ccJAA5vVIt2Yq190OmUDzWpo3lEKU',
    appId: '1:941925661587:android:c28151ca996d3c8d7ac666',
    messagingSenderId: '941925661587',
    projectId: 'jukebox-996de',
    databaseURL: 'https://jukebox-996de-default-rtdb.firebaseio.com',
    storageBucket: 'jukebox-996de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpGgk5YiFAQ0VO38WjlcgWhQJ-km-5fnA',
    appId: '1:941925661587:ios:1bfb082ceee00f0c7ac666',
    messagingSenderId: '941925661587',
    projectId: 'jukebox-996de',
    databaseURL: 'https://jukebox-996de-default-rtdb.firebaseio.com',
    storageBucket: 'jukebox-996de.firebasestorage.app',
    iosClientId: '941925661587-5nr9m7ke9jjrhoci5tu5f6gmj8aj0pnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.welcometothedisco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpGgk5YiFAQ0VO38WjlcgWhQJ-km-5fnA',
    appId: '1:941925661587:ios:1bfb082ceee00f0c7ac666',
    messagingSenderId: '941925661587',
    projectId: 'jukebox-996de',
    databaseURL: 'https://jukebox-996de-default-rtdb.firebaseio.com',
    storageBucket: 'jukebox-996de.firebasestorage.app',
    iosClientId: '941925661587-5nr9m7ke9jjrhoci5tu5f6gmj8aj0pnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.welcometothedisco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCMP6ofhmSc5juKEbkRkSxvWWFUe800P4',
    appId: '1:941925661587:web:0e619334e2d4436c7ac666',
    messagingSenderId: '941925661587',
    projectId: 'jukebox-996de',
    authDomain: 'jukebox-996de.firebaseapp.com',
    databaseURL: 'https://jukebox-996de-default-rtdb.firebaseio.com',
    storageBucket: 'jukebox-996de.firebasestorage.app',
    measurementId: 'G-57KJS30CD7',
  );
}
